/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/woman.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Woman = (props) => {
  // const { nodes, materials } = useGLTF('/woman.gltf')
  const { nodes, materials, animations } = useGLTF("./models/woman.gltf");
  
  return (
    <group {...props} dispose={null}>
      <group position={[-0.008, 0, -0.005]} rotation={[0, -1.113, 0]}>
        <group position={[0, 1.063, -0.035]} rotation={[-1.465, 1.571, 0]}>
          <primitive object={nodes.Hip} />
          <primitive object={nodes.Ribs} />
        </group>
        <skinnedMesh geometry={nodes.Robot.geometry} material={materials['Robot_Color 1']} skeleton={nodes.Robot.skeleton} />
      </group>
    </group>
  )
}

export default Woman;

useGLTF.preload("./models/scene.gltf");
