/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/woman.gltf 
Author: alonecat06 (https://sketchfab.com/alonecat06)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-kyle-2fb613916efb45c08c3a1337b20e9d3c
Title: Robot Kyle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

const Woman = (props) => {

  const { nodes, materials } = useGLTF('./models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Robot} />
    </group>
  )
}

export default Woman;
useGLTF.preload('./models/scene.gltf')
